### ISSUE TITLE
Parece piada...

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/CRP#1]
Eu não acho que trocar um dígito por duas letras seja algo sério. Continua sendo o mesmo esquema e os mesmos dados dos Correios.

**Comment by ppKrauss** [comment]
Oi @alexandre-mbm é a troca de uma piada, a nossa "Lei" inconstitucional, por outra piada, a nossa "troca de 6 por meia dúzia". O importante é que nos livramos do problema de direito autoral. É muito comum por exemplo na proteção de marca registrada ou patente de padrões (ex. gif) você trocar uma firula para não colidir com "o dono".

**Comment by alexandre-mbm** [comment]
> O importante é que nos livramos do problema de direito autoral.

Será que livra mesmo?!

> É muito comum por exemplo na proteção de marca registrada ou patente de padrões (ex. gif) você trocar uma firula para não colidir com "o dono".

Até que os advogados colem...

**Comment by ppKrauss** [comment]
> Será que livra mesmo?!

Sim!! O projeto foi concebido a depois de consultas jurídicas apontarem para a solução. O risco de o Correio reclamar também é baixo, pois se a lei de 1977 for revista eles perdem outros monopólios muito mais rentáveis que a base do CEP.
